version: "3.7"
services:
  loginapp:
        container_name: nodeloginapp-mongo
        image: node-loginapp:v1
        restart: always
        build: .
        environment: 
              MY_DB: mongodb://mongo_db_host:27017/loginapi
        ports:
          - "82:8080"
        depends_on: 
          - mongo
        links: 
          - mongo:mongo_db_host
  mongo:
        image: mongo
        restart: always