apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
      tier: frontend
  template:
    metadata:
      labels:
        app: login
        tier: frontend
    spec:
      containers:
        - name: app
          image: node-loginapp:v1
          ports:
            - containerPort: 8080
          env:
            - name: MY_DB
              value: mongodb://mongo:27017/dev

---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  selector:
    app: login
    tier: frontend

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort